// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniLocalizer.Demo.Models;

namespace UniLocalizer.Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191129100917_ColumnTypesAdded")]
    partial class ColumnTypesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniLocalizer.Demo.Models.LocalizerResourceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Culture")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("LocationKey")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ResourceKey")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("ResourceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
